actions:
  pre:
    vim-plug-install: test -e ~/.vim/autoload/plug.vim || (mkdir -p ~/.vim/autoload;
      curl -fLo ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim)
    init_brew_xcode: sh actions/init_brew_xcode.sh
    init_yabai: brew install koekeishiya/formulae/yabai && brew install koekeishiya/formulae/skhd
    init_zinit: mkdir ~/.zinit && git clone https://github.com/zdharma/zinit.git ~/.zinit/bin
    install_python: sh actions/python.sh
    install_neovim: sh actions/nvim_python.sh
    config_mac:
      EXEPATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)
      CWD=${EXEPATH}/system osascript -e 'tell application "System Preferences" to
      quit' > /dev/null 2>&1 /bin/bash ${CWD}/darwin.sh
    init_ssh: sh actions/ssh_keys.sh
  install_packages: sh actions/install_packages.sh
  vim-plug: vim +PlugInstall +qall
  vscode-install-extensions: >-
    xargs -n 1 code --force --install-extension < {0}
  post:
    start_zinit: source ~/.zinit/bin/zinit.zsh; exec $SHELL; zinit self-update
    start_yabai: brew services start skhd && brew services start yabai
    auto_update_yabai: YABAI_CERT=yabai-cert sh -c "$(curl -fsSL "https://git.io/update-yabai")" &
    hostname: sh actions/hostname.sh
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: true
  workdir: ~/.config/dotdrop
  link_on_import: nolink
  minversion: 0.31.0
dynvariables:
  os_name: uname
dotfiles:
  f_alias:
    dst: ~/.alias
    src: alias
    link: link
  f_functions:
    dst: ~/.functions
    src: functions
    link: link
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
    link: link
  f_matplotlibrc:
    dst: ~/.matplotlib/matplotlibrc
    src: matplotlib/matplotlibrc
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
    link: link
  f_tool-versions:
    dst: ~/.tool-versions
    src: tool-versions
  f_zshenv:
    dst: ~/.zshenv
    src: zshenv
    link: link
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
    link: link
  f_skhdrc:
    src: skhdrc
    dst: ~/.skhdrc
    link: link
  f_yabairc:
    src: yabairc
    dst: ~/.yabairc
    link: link
  f_yank.sh:
    src: yank.sh
    dst: ~/yank.sh
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
    link: link
    actions:
      - vim-plug-install
      - vim-plug
  d_vim:
    src: vim
    dst: ~/.vim/
    link: link_children
  d_hammerspoon:
    src: hammerspoon
    dst: ~/.hammerspoon
    link: link
  f_tmux.remote.conf:
    src: tmux.remote.conf
    dst: ~/.tmux.remote.conf
    link: link
  d_firefox:
    src: config/firefox
    dst: ~/.config/firefox
  d_iterm:
    src: config/iterm
    dst: ~/.config/iterm
  f_karabiner.json:
    src: config/karabiner/karabiner.json
    dst: ~/.config/karabiner/karabiner.json
    chmod: "600"
  f_ctags:
    src: ctags
    dst: ~/.ctags
  f_spoof_mac_address.sh:
    src: config/spoof_mac_address.sh
    dst: ~/.config/spoof_mac_address.sh
  f_gitignore:
    src: gitignore
    dst: ~/.gitignore
    link: link
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
    link: link
  f_run_pyls_with_venv:
    src: config/run_pyls_with_venv.sh
    dst: ~/.config/run_pyls_with_venv.sh
    chmod: "744"
  f_pycodestyle:
    src: config/pycodestyle
    dst: ~/.config/pycodestyle
  f_jupyter_qtconsole_config:
    src: jupyter/jupyter_qtconsole_config.py
    dst: ~/.jupyter/jupyter_qtconsole_config.py
  f_ipython_config:
    src: ipython/profile_default/ipython_config.py
    dst: ~/.ipython/profile_default/ipython_config.py
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
    chmod: "775"
    link: link_children
  f_vscode_settings.json:
    dst: ~/.vscode/settings.json
    src: vscode/settings.json
    link: link
  f_vscode_extensions.txt:
    src: vscode/vscode-extensions.txt
    dst: "{{@@ vscode_tmp_dst @@}}"
    actions:
      # This action installs VSCode extensions listed in the dotfile on-the-fly
      - vscode-install-extensions '{{@@ vscode_tmp_dst @@}}'
    # This transformation actually creates the dotfile.
    trans_write: vscode-list-extensions
  f_hosts:
    src: etc/hosts
    dst: /etc/hosts
profiles:
  casper-03:
    dotfiles:
      - f_tmux.conf
      - f_zshrc
      - f_zshenv
      - f_alias
      - f_functions
      - f_tool-versions
      - f_matplotlibrc
      - f_gitconfig
      - f_vscode_settings.json
      - f_skhdrc
      - f_yabairc
      - f_vimrc
      - f_tmux.remote.conf
      - f_karabiner.json
      - f_ctags
      - f_spoof_mac_address.sh
      - f_gitignore
      - f_starship.toml
      - f_run_pyls_with_venv
      - d_vim
      - d_firefox
      - d_hammerspoon
      - d_iterm
      - d_nvim
      - f_hosts
  darwin:
    dotfiles:
      - f_ctags
      - f_spoof_mac_address.sh
      - d_iterm
      - d_firefox
      - d_hammerspoon
      - f_karabiner.json
    # actions:
    #   - init_brew_xcode
    #   - install_packages
    #   - config_mac
    #   - hostname
  git:
    dotfiles:
      - f_gitconfig
      - f_gitignore
    actions:
      - init_ssh
  zsh:
    dotfiles:
      - f_zshenv
      - f_zshrc
      - f_tmux.conf
      - f_tmux.remote.conf
      - f_starship.toml
      - f_alias
      - f_functions
    actions:
      - init_zinit
      - start_zinit
  win_manager:
    dotfiles:
      - f_skhdrc
      - f_yabairc
    actions:
      - init_yabai
      - start_yabai
      - auto_update_yabai
  neovim:
    dotfiles:
      - d_nvim
    actions:
      - install_neovim
  python:
    dotfiles:
      - f_run_pyls_with_venv
      - f_jupyter_qtconsole_config
      - f_tool-versions
      - f_ipython_config
      - f_pycodestyle
      - f_matplotlibrc
    actions:
      - install_python
  vscode:
    dotfiles:
      - f_vscode_extensions.txt
      - f_vscode_settings.json
    dynvariables:
      vscode_tmp_dst: mktemp /tmp/vscode-tmp.XXX
    variables:
      is_headless: false
  vim:
    dotfiles:
      - f_vimrc
trans_write:
  vscode-list-extensions: code --list-extensions > {1}
